# Generated by Django 5.0 on 2023-12-23 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.userprofile'),
        ),
    ]
