# Generated by Django 4.2.8 on 2023-12-23 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='setup.test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testattempt',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='setup.test'),
            preserve_default=False,
        ),
    ]
