# Generated by Django 4.2.8 on 2023-12-24 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_remove_question_subject_question_test_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testattempt',
            old_name='user',
            new_name='user_profile',
        ),
    ]
