# Generated by Django 4.2.8 on 2023-12-24 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_rename_user_testattempt_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='setup.userprofile'),
            preserve_default=False,
        ),
    ]
