# Generated by Django 4.2.8 on 2023-12-24 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
        ('setup', '0009_useranswer_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattempt',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
