# Generated by Django 5.0.2 on 2024-02-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0013_alter_testattempt_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='selected_option',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
